### ISSUE TITLE
Error mesages

### ISSUE THREAD

**Issue by timarney** [cds-snc/list-manager#130]
Ensure details error messaged are returned when issues happen with Notify calls 

To start --- if we pass a template that doesn't exist for a service and Notify fails to send.

**Comment by falila** [comment]
In regards to `fails to send` statement i was thinking that maybe you're refering  to the status of a notification which may required using callbacks?  Otherwise i've assumed that only technical issues like unhandled exceptions.Also errors like `HTTPError` returned from calling `send_email_notification`  and `send_sms_notification`.
